### 1. 보컬 분석 요청 (POST)
# @name requestAnalysis
POST http://localhost:8080/api/v1/analyze
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="userId"

1
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test_vocal.m4a"
Content-Type: audio/mpeg

< ./test_vocal.m4a
--WebAppBoundary--

###

### 2. 분석 상태 조회 (GET/Polling)
# @name getStatus
# 아래 {{taskId}} 부분에 1번 요청에서 받은 UUID를 직접 붙여넣으세요.
GET http://localhost:8080/api/v1/analyze/9e2a8394-5876-45a0-9533-370ec51be624/status
Accept: application/json